_BASE_: Base-RCNN-FPN_resnet50.yaml
MODEL:
  ROI_HEADS:
    NAME: "StandardROIHeadsScores"
    NUM_CLASSES: 4
    BATCH_SIZE_PER_IMAGE: 1024
    NMS_THRESH_TEST: 0.3
  META_ARCHITECTURE: "GeneralizedRCNN"
  RPN:
    PRE_NMS_TOPK_TEST: 2000
    PRE_NMS_TOPK_TRAIN: 1000
    POST_NMS_TOPK_TRAIN: 1000
    POST_NMS_TOPK_TEST: 1000
    BATCH_SIZE_PER_IMAGE: 1024
  BACKBONE:
    NAME: "build_resnet_fpn_backbone"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
SOLVER:
  BASE_LR: 0.003
  WARMUP_ITERS: 1000
  LR_SCHEDULER_NAME: "WarmupMultiStepLR"
  CHECKPOINT_PERIOD: 10000
  MAX_ITER: 1000000
  STEPS: 400000,600000
DATALOADER:
  NUM_WORKERS: 8
TEST:
  DETECTIONS_PER_IMAGE: 50
DATASETS:
  TRAIN: ('Chancery_train',)
  TEST: ('Chancery_test',)